### ISSUE TITLE
Enable install to iOS

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#209] opened 2022-04-08 08:13 UTC
A PWA should be installable to iOS phones.

**Comment by Tushar-4781** [comment] 2023-01-12 07:26
@tijlleenders can we close this ?

**Comment by tijlleenders** [comment] 2023-01-12 16:54
No, it is still important to do at some point but I'll add a low prio label

**Comment by Tushar-4781** [comment] 2023-02-28 07:21
@tijlleenders #678 is duplicate of this ig ?

**Comment by tijlleenders** [comment] 2023-02-28 16:35
Yes this is a duplicate.

**Closed** 2023-02-28 16:34 UTC
Labels: feature, ease of use, low prio
