### ISSUE TITLE
GitHub actions or Vercel

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#42] opened 2022-01-29 06:42 UTC
How are credits measured with GitHub actions?
Are being a public repository with an OSI license the only conditions to receive free actions?
How much per what time period can we use for free? There must be a limit built-in.

**Comment by mallikarai05** [comment] 2022-01-31 16:03
It is completely free, you can check the following link for more details if needed.

**Comment by mallikarai05** [comment] 2022-01-31 16:07
For setting up the CD, I would need to know where is the website hosted.

**Comment by tijlleenders** [comment] 2022-01-31 19:10
I think you can use GitHub pages for the dev site. If OK I can deploy via
AWS.

**Comment by mallikarai05** [comment] 2022-02-01 06:45
Okay, for the dev site I will set up the GitHub pages.
How exactly will the production release get deployed on AWS? I would need to set up a CD pipeline for that too so if you could provide more details.

**Comment by tijlleenders** [comment] 2022-02-01 11:07
Best to focus on the pipeline up to dev for now.

From dev to prod it will be a 'auto deploy on demand'.
Not sure yet if it is better to have this 'button' on the GitHub side or on the AWS side.

**Comment by tijlleenders** [comment] 2022-02-01 11:09
Great to hear GitHub actions are really free.
Feel free to close this issue if you have no more questions.

**Comment by mallikarai05** [comment] 2022-02-02 06:45
Okay, I'll start working accordingly.

**Comment by tijlleenders** [comment] 2022-03-18 17:03
Pulkit recommended switching from Github Actions to Vercel. They have an OSS policy subject to conditions:
Vercel is committed to enabling the creation, adoption, and development of open source projects. As such, Vercel offers the option to sponsor these projects, covering the costs of hosting them in full.

To obtain sponsorship for a project, first confirm that the criteria below are met, then contact our Product Advocacy team by emailing directly at sponsorships@vercel.com.

Sponsorship Criteria

There are some minor criteria that are required to be fulfilled before Vercel can sponsor your project, these are listed below:

The project should be non-commercial.

The project should be open source.

The project should not use Turborepo, and not be part of a monorepo with commercial projects.

A Vercel banner in the footer of each site page.

A Vercel banner in the source repository's README.md file.

All links back to Vercel should use a UTM tag with the format: ?utm_source=[team-name]&utm_campaign=oss.

Aside from using the Vercel banner provided below, you can also use the Vercel logo prefixed with the words "Powered by".

@pulkitvyas08 Can you tell us why Vercel is better than Github Actions?

**Comment by tijlleenders** [comment] 2022-03-18 17:10
"A Vercel banner in the footer of each site page." 

Not sure how to interpret this for a PWA.

Also, the strict non-commercial could be problematic if we ever want to offer add-on services like paid backup.

**Comment by tijlleenders** [comment] 2022-03-18 17:30
Vercel is more of a CDN on top of CICD it seems.

I was thinking AWS Cloudfront for CDN but we'll have to re-evaluate the costs at scale after the free credits expire.

**Comment by pulkitvyas08** [comment] 2022-03-19 05:37
> 

I don't think that we need to go with the sponsored route at the moment. Just the hobby subscription would be enough for the development and testing phase of the app and then when we need scaling we can go with some cloud provider

**Comment by tijlleenders** [comment] 2022-03-19 11:22
I'm comfortable and have experience with CICD and CDN on AWS.

Just to be clear: I'm open to switching to Vercel - I'm just trying to understand the reason why this is important.

Is it price or features?
If it is features: what features?

**Comment by pulkitvyas08** [comment] 2022-03-19 11:26
Both pricing and features but at the moment just a few features -
- Ready-made CI/CD environment that can be modified without many issues
- Separate URLs for each PR and subsequent commits on those PRs to visually test out the changes
- Fast refresh compared to a lot of other hosting solutions

**Comment by tijlleenders** [comment] 2022-03-20 11:17
1. Ready-made CI/CD environment that can be modified without many issues
That's nice - but Github Actions seems pretty easy to configure too.
Is it that you're more familiar with Vercel vs Github Actions or is Vercel fundamentally better?

2. Separate URLs for each PR and subsequent commits on those PRs to visually test out the changes
So it deploys to a staging website with alternate URL? What is the advantage - manual access?

3. Fast refresh compared to a lot of other hosting solutions
Not very important in my opinion. Since ZinZen is offline first - we can develop locally and don't need a fast CICD for the dev loop. 
Whenever a commit is made to the central repo - it has been locally tested and good to go in nearly all cases.
For AWS - all CDN caches can be invalidated / refreshed with a single HTTP request.

**Comment by pulkitvyas08** [comment] 2022-03-20 11:23
> 

1. Yes, no fundamental advantage over GA but the simplicity has a certain appeal

2. The advantage is manual testing of new PRs and changes to the source code. Currently, we cannot review the changes that a PR would make (visually and functionally) before merging the PR. This is extremely dangerous as the PR might introduce some breaking changes and render the prod version unusable

3. When I am making this suggestion I am only considering the dev build. For prod we can use some other branch

**Comment by tijlleenders** [comment] 2022-03-20 12:33
Let's discuss Vercel on Friday.

Breaking changes should be caught by having a good Cypress test suite.
If these tests break screenshots can provide the insight too: https://github.com/jaredpalmer/cypress-image-snapshot/issues/211

That said I'm up for Vercel if it makes our life easier, is free, doesn't include ads/obligations and is not too much work.

**Comment by tijlleenders** [comment] 2022-03-25 16:51
Checked the Vercel docs and looks like a really good suggestion.

https://vercel.com/docs/concepts/limits/fair-use-policy: "Asking for Donations does not fall under commercial usage."
So we're good with a hobby account.

Just created one and linked the ZinZen repo.
Probably need to adjust the build settings:
![image](https://user-images.githubusercontent.com/44887755/160165576-bf1df974-c205-47c7-bfbb-f88cb8638707.png)

**Comment by pulkitvyas08** [comment] 2022-03-27 09:28
Most warnings are because of incompatible versions between various NPM packages. This is very common in most NPM dependent projects on the internet as some libraries go on without releasing new versions for months. 

Now the build failure is rather odd. Let me create a local build and see if I get the same issue

**Comment by tijlleenders** [comment] 2022-04-01 04:40
Vercel doesn't build a working site at the moment.
I get a blank screen showing "Your browser needs to enable javascript" even though js is enabled.

Also some Vercel builds seem to go on forever (11h!):
![image](https://user-images.githubusercontent.com/44887755/161196011-a04d8f1d-a6ee-419f-bafd-2c782167c681.png)

**Comment by pulkitvyas08** [comment] 2022-04-01 08:29
On it. Will fix ASAP

**Comment by pulkitvyas08** [comment] 2022-04-01 08:29
As for the builds taking more than 10mins we can cap them as they probably have errors in them

**Comment by pulkitvyas08** [comment] 2022-04-01 10:10
@tijlleenders check out this link https://zinzen.vercel.app/[ZinZen](https://zinzen.vercel.app/ZinZen). The issue is that the landing page + dashboard is currently pointing at `/ZinZen` and `/home` which was needed to be done for GitHub pages deployment AFAIK. Now since we have a dedicated domain (the Vercel one), we don't need these. @mallikarai05 please create an issue around this and fix it ASAP

**Comment by pulkitvyas08** [comment] 2022-04-01 10:11
Updated the broken link ^^^

**Comment by pulkitvyas08** [comment] 2022-04-05 06:47
Closing as Vercel is setup and working fine

**Closed by pulkitvyas08** 2022-04-05 06:47 UTC
Labels: devops
