### ISSUE TITLE
Fix contrast in sharing dialog

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#2073] opened 2024-11-08 07:18 UTC
**Describe the bug**
The Contact name placeholder is not visible (enough):  
![image](https://github.com/user-attachments/assets/fd3c6aff-b9e2-493b-9e2d-193d596cf6a5)

**To Reproduce**

1. Go to a Goal
2. Click on Share
3. Copy the link
4. Open the link in a different browser (context)

**Expected behavior**
Placeholder has enough contract to comply to accessibility guidelines.

**Additional context**
None.

**Comment by vinaybadgujar102** [comment] 2024-11-10 14:52
@tijlleenders duplicate of #2012

**Comment by tijlleenders** [comment] 2024-11-10 14:57
I knew it - but couldn't find it via search!  
Thanks for catching the duplicate. Will delete this one.

**Closed** 2024-11-10 14:57 UTC
Labels: bug, good first issue, low prio
