### ISSUE TITLE
Implement impossible to schedule in UI

### ISSUE THREAD

**Issue by tijlleenders** [tijlleenders/ZinZen#896] opened 2023-01-06 06:14 UTC
Show impossible only when present.
Implement similar to MyGoals/Inbox UI.

**Comment by tijlleenders** [comment] 2023-01-06 06:14
Blocked by https://github.com/tijlleenders/ZinZen/issues/882

**Comment by Tushar-4781** [comment] 2023-01-28 18:53
Duplicate of #968 
Resolved by #969

**Closed by Tushar-4781** 2023-01-28 18:53 UTC
Labels: UI
